name: Build and Publish Python packages [PyPi]
run-name: Build laser-mind-client Python package by @${{ github.actor }}

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - pypi
#   pull_request:
#     branches:
#       - pypi

on: [push]

jobs:
  checkout:
    runs-on: [ lightsolver-github-runner ]
    steps:
      - uses: hmarr/debug-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout github-actions repository
        uses: actions/checkout@v3
        with:
          repository: LightSolverInternal/github-actions
          token: ${{ secrets.TOKEN }}
          path: reusable-actions

  build-python-packages:
    runs-on: [ lightsolver-github-runner ]
    needs: checkout
    env:
      AWS_REGION: "eu-central-1"
      CODE_ARTIFACT_REPOSITORY_NAME: "general-pypi-repo"
      CODE_ARTIFACT_DOMAIN_NAME: "ls-prod"
      AWS_ACCOUNT_OWNER_ID: "541441380680"
    permissions:
      id-token: write 

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Tag and Set version
        id: tag-set-version
        uses: ./reusable-actions/tag-set-python-package-version
        with:
          github_token: ${{ secrets.TOKEN}}
          default_bump: "minor"

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Get PYPI_TOKEN form AWS SSM
        uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.3.2
        with:
          ssm-path: /ls/pypi/token #will get as PYPI_TOKEN

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: $PYPI_TOKEN
          repository-url: https://test.pypi.org/laser-mind-client/